# Generated by Django 4.1.6 on 2023-02-10 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="pet",
        ),
    ]
